### ISSUE TITLE
Need a better UI

### ISSUE THREAD

**Issue by Himanshuranjan30** [Himanshuranjan30/Mood-Diary-Flutter#3]
Anyone who can work on the app UI can work on it. Till now its pretty basic.

**Comment by cyber-venom003** [comment]
Can I work on this as soon as Hacktoberfest starts??

**Comment by Himanshuranjan30** [comment]
Sure,Go ahead! @cyber-venom003

**Comment by cyber-venom003** [comment]
![Screenshot_1601372949](https://user-images.githubusercontent.com/58390399/94543365-9a630600-0267-11eb-9f7b-784752c4c07a.png)

@Himanshuranjan30 Any reviews about it? Should I make the PR of this??

**Comment by Himanshuranjan30** [comment]
Yea looks good @cyber-venom003

**Comment by desaihetav** [comment]
I'd love to work on the UI. Can I contribute as a part of Hacktoberfest?

**Comment by Himanshuranjan30** [comment]
sure! go ahead @desaihetav

**Comment by desaihetav** [comment]
> sure! go ahead @desaihetav 

Great thanks! @Himanshuranjan30
