### ISSUE TITLE
align all the 3 images in a single row in the documentation readme file.

### ISSUE THREAD

**Issue by Himanshuranjan30** [Himanshuranjan30/Mood-Diary-Flutter#5]

**Comment by hpnightowl** [comment]
can i take  this issue?

**Comment by Himanshuranjan30** [comment]
Sure @hpnightowl

**Comment by hpnightowl** [comment]
issue stilll there or completed?

**Comment by Himanshuranjan30** [comment]
You can @hpnightowl

**Comment by hpnightowl** [comment]
#12

**Comment by hpnightowl** [comment]
can you close this issue if it's over or any more changes needed?

**Comment by hpnightowl** [comment]
Hi! @Himanshuranjan30 Can you make it Hacktoberfest friendly ? like below guidelines'
 
Submitted in a public repo AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
